name: jcouch
favicon: null
layout_spectrum: 0.8515823704656214
typography_spectrum: 0.9650346271228045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6684774309396744
  lightness: 0.8208871961105615
  saturation: 0.5975669464096427
  rhythmicContrast: 0.31733095017261803
purpose: []
